version: '3.9'

services:

  mysql:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

    restart: unless-stopped

  adminer:
    image: adminer

    restart: unless-stopped

    ports:
      - "${ADMINER_PORT}:8080"

    depends_on:
      - mysql

  clients-service:
    build:
      context: ./clients

    restart: unless-stopped

    depends_on:
      - mysql

    ports:
      - "${CLIENTS_BACK_PORT}:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${USERS_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  products-service:
    build:
      context: ./products

    restart: unless-stopped

    depends_on:
      - mysql

    ports:
      - "${PRODUCTS_BACK_PORT}:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${PRODUCTS_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  sales-service:
    build:
      context: ./sales

    restart: unless-stopped

    depends_on:
      - mysql

    ports:
      - "${SALES_BACK_PORT}:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${SALES_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CLIENTS_SERVICE_URI: http://clients-service:8080
      PRODUCTS_SERVICE_URI: http://products-service:8080

  gateway-service:
    build:
      context: ./gateway

    restart: unless-stopped

    depends_on:
      - clients-service
      - products-service
      - sales-service

    ports:
      - "${GATEWAY_PORT}:8080"

    environment:
      CLIENTS_SERVICE_URI: http://clients-service:8080
      PRODUCTS_SERVICE_URI: http://products-service:8080
      SALES_SERVICE_URI: http://sales-service:8080

volumes:
  mysql_data: