spring:
  application:
    name: GatewayMicroservice

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: clients-service
              uri: ${CLIENTS_SERVICE_URI:http://clients-service:8080}
              predicates:
                - Path=/clients/**

            - id: products-service
              uri: ${PRODUCTS_SERVICE_URI:http://products-service:8080}
              predicates:
                - Path=/products/**

            - id: sales-service
              uri: ${SALES_SERVICE_URI:http://sales-service:8080}
              predicates:
                - Path=/sales/**

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: read-only
