apiVersion: v1
kind: ConfigMap

metadata:
  name: sales-config

data:
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: sales_db
  CLIENTS_SERVICE_URI: http://clients-service:8080
  PRODUCTS_SERVICE_URI: http://products-service:8080