apiVersion: v1
kind: ConfigMap

metadata:
  name: gateway-config

data:
  SERVER_PORT: "8080"
  CLIENTS_SERVICE_URI: http://clients-service:8080
  PRODUCTS_SERVICE_URI: http://products-service:8080
  SALES_SERVICE_URI: http://sales-service:8080